# Generated by Django 6.0.6 on 2026-06-14 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('Staff_POS', 'Staff POS'), ('Waiter_App', 'Waiter App'), ('User_App_QR', 'User App QR'), ('ONDC', 'ONDC'), ('Web_Direct', 'Web Direct')], db_index=True, default='Staff_POS', max_length=20),
        ),
    ]
