# Generated by Django 6.0.6 on 2026-06-20 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staffattendance_clock_out_distance'),
        ('orders', '0002_order_created_by_alter_order_source'),
        ('tables', '0002_add_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('location', 'idempotency_key'), name='uniq_order_idempotency_key'),
        ),
    ]
