# Generated by Django 5.2.3 on 2026-06-20 13:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_staffattendance_clock_out_distance'),
        ('menu', '0005_alter_variant_tax_group_menulistingvariantprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_categories', to='core.restaurant')),
            ],
            options={
                'verbose_name_plural': 'ingredient categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name, e.g. "Kilogram"', max_length=60)),
                ('short_name', models.CharField(help_text='Abbreviation, e.g. "kg"', max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='1 of THIS unit = <factor> of base_unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('base_unit', models.ForeignKey(blank=True, help_text='The base unit this converts into (NULL = this IS the base unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='inventory.inventoryunit')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='core.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.restaurant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='inventory.ingredientcategory')),
                ('unit', models.ForeignKey(help_text='Primary tracking unit (e.g. kg, L, piece)', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='inventory.inventoryunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(help_text='Auto-generated: PO-{location_code}-{seq}', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=25)),
                ('order_date', models.DateField(help_text='Date the PO was created / placed')),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.location')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('received_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Expected unit price when ordering', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('received_unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Actual unit price on receipt (may differ from expected)', max_digits=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.ingredient')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(help_text='Auto-generated if blank: RECV-{loc_code}-{date}-{seq}', max_length=60)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=4, help_text='Original quantity received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('remaining_quantity', models.DecimalField(decimal_places=4, help_text='Current remaining after FIFO consumption', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Cost per unit at time of receipt', max_digits=10)),
                ('fssai_mfg_license', models.CharField(blank=True, help_text="Supplier's manufacturing license (FSSAI compliance)", max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('consumed', 'Consumed'), ('wasted', 'Wasted')], db_index=True, default='active', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.location')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.ingredient')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.purchaseorderitem')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Optional label (auto-set from menu item if blank)', max_length=120)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.menuitem')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.variant')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity consumed per 1 serving', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.recipe')),
                ('unit', models.ForeignKey(help_text='Unit for this recipe line (should be convertible to ingredient.unit)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryunit')),
            ],
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current on-hand quantity in ingredient.unit', max_digits=12)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='Alert when quantity drops below this value', max_digits=12, null=True)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=4, help_text='Suggested quantity at which to reorder', max_digits=12, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Suggested quantity to order when reorder_point is reached', max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current cost per unit (weighted avg or latest price)', max_digits=10)),
                ('cost_method', models.CharField(choices=[('weighted_average', 'Weighted Average'), ('latest_price', 'Latest Price')], default='weighted_average', max_length=20)),
                ('last_restocked_at', models.DateTimeField(blank=True, help_text='Timestamp of last purchase receipt for this ingredient', null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('manual_adjustment', 'Manual Adjustment'), ('order_deduction', 'Order Deduction'), ('wastage', 'Wastage'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('opening_stock', 'Opening Stock'), ('physical_count', 'Physical Count')], db_index=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='+ve = stock in, −ve = stock out', max_digits=12)),
                ('quantity_before', models.DecimalField(decimal_places=4, help_text='StockLevel.quantity before this movement', max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=4, help_text='StockLevel.quantity after this movement', max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Per-unit cost at time of movement (for receipt/wastage costing)', max_digits=10, null=True)),
                ('reference_type', models.CharField(blank=True, db_index=True, help_text='Source entity type: purchase_order, transfer, wastage, order, adjustment', max_length=30)),
                ('reference_id', models.UUIDField(blank=True, help_text='PK of the source entity', null=True)),
                ('reason', models.CharField(blank=True, choices=[('physical_count', 'Physical Count Correction'), ('untracked_usage', 'Untracked Usage'), ('other', 'Other')], help_text='Adjustment reason (only for manual_adjustment / physical_count)', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.batch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_number', models.CharField(help_text='Auto-generated: TRF-{date}-{seq}', max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=25)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.location')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Sender can approve a partial amount', max_digits=12, null=True)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.ingredient')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, help_text='GSTIN', max_length=20)),
                ('fssai_license', models.CharField(blank=True, help_text='FSSAI license number (F-70 compliance)', max_length=20)),
                ('payment_terms', models.TextField(blank=True, help_text='e.g. "Net 30"')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='0.00 – 5.00', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_price', models.DecimalField(blank=True, decimal_places=4, help_text='Last known / negotiated price per unit', max_digits=10, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Typical delivery time in days', null=True)),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark one supplier as preferred per ingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='inventory.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_ingredients', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='WastageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='qty × unit_cost at time of waste', max_digits=10)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('over_prepared', 'Over-Prepared'), ('dropped', 'Dropped'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logs', to='inventory.batch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_logs', to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_logs', to='core.location')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wastage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ingredientcategory',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='uniq_ingredient_category_name_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryunit',
            constraint=models.UniqueConstraint(fields=('short_name', 'restaurant'), name='uniq_inv_unit_shortname_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='uniq_ingredient_name_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__gt', Decimal('0'))), name='poitem_ordered_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', Decimal('0'))), name='poitem_received_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('menu_item', 'variant'), name='uniq_recipe_item_variant'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='uniq_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='recipe_ingredient_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['location', 'quantity'], name='idx_stocklevel_location_qty'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('ingredient', 'location'), name='uniq_stocklevel_ingredient_location'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0'))), name='stocklevel_quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location', 'ingredient', 'created_at'], name='idx_movement_loc_ingr_date'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_movement_reference'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_location', 'status'], name='idx_transfer_from_status'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_location', 'status'], name='idx_transfer_to_status'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', Decimal('0'))), name='transferitem_requested_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='uniq_supplier_name_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', Decimal('0')), ('rating__lte', Decimal('5'))), _connector='OR'), name='supplier_rating_range'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['location', 'status'], name='idx_po_location_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('po_number', 'location'), name='uniq_po_number_location'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['location', 'ingredient', 'status'], name='idx_batch_loc_ingr_status'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='idx_batch_expiry'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('batch_number', 'location'), name='uniq_batch_number_location'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', Decimal('0'))), name='batch_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplieringredient',
            constraint=models.UniqueConstraint(fields=('supplier', 'ingredient'), name='uniq_supplier_ingredient'),
        ),
        migrations.AddIndex(
            model_name='wastagelog',
            index=models.Index(fields=['location', 'ingredient', 'created_at'], name='idx_wastage_loc_ingr_date'),
        ),
        migrations.AddIndex(
            model_name='wastagelog',
            index=models.Index(fields=['reason'], name='idx_wastage_reason'),
        ),
    ]
