# Generated by Django 5.2.3 on 2026-06-21 05:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0006_menu_inventory_recipe_links'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='uniq_recipe_item_variant',
        ),
        migrations.AddField(
            model_name='recipe',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.modifier'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='effect',
            field=models.CharField(choices=[('add', 'Add'), ('subtract', 'Subtract')], default='add', help_text='Add increases consumption; subtract removes (e.g. "No onion")', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label (auto-set from target if blank)', max_length=120),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Quantity per 1 serving / modifier selection', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('modifier__isnull', True)), fields=('menu_item', 'variant'), name='uniq_recipe_item_variant'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('modifier__isnull', False)), fields=('modifier',), name='uniq_recipe_modifier'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', True), ('modifier__isnull', False), ('variant__isnull', True)), models.Q(('menu_item__isnull', False), ('modifier__isnull', True), ('variant__isnull', True)), models.Q(('menu_item__isnull', False), ('modifier__isnull', True), ('variant__isnull', False)), _connector='OR'), name='recipe_valid_target'),
        ),
    ]
