# Generated by Django 6.0.6 on 2026-06-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_menu_inventory_recipe_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('manual_adjustment', 'Manual Adjustment'), ('order_deduction', 'Order Deduction'), ('order_reversal', 'Order Reversal'), ('wastage', 'Wastage'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('opening_stock', 'Opening Stock'), ('physical_count', 'Physical Count')], db_index=True, max_length=30),
        ),
    ]
