# Generated by Django 6.0.6 on 2026-06-21 06:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staffattendance_clock_out_distance'),
        ('inventory', '0003_alter_stockmovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('shelf_life_hours', models.PositiveIntegerField(blank=True, help_text='Hours a production batch stays good (sets batch expiry).', null=True)),
                ('standard_batch_yield', models.DecimalField(blank=True, decimal_places=4, help_text='Typical output of one production run, in unit (UI default).', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreparedItemComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Raw quantity per 1 unit of prepared output', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
            ],
        ),
        migrations.CreateModel(
            name='PreparedStockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Current on-hand quantity in prepared_item.unit', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Weighted-average production cost per unit', max_digits=10)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparedStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('production_output', 'Production Output'), ('order_deduction', 'Order Deduction'), ('order_reversal', 'Order Reversal'), ('wastage', 'Wastage'), ('expiry', 'Expiry'), ('manual_adjustment', 'Manual Adjustment')], db_index=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_before', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(help_text='Auto-generated if blank: PROD-{loc}-{date}-{seq}', max_length=60)),
                ('produced_quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('remaining_quantity', models.DecimalField(decimal_places=4, help_text='Current remaining after FIFO consumption', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Raw component cost ÷ produced_quantity', max_digits=10)),
                ('produced_at', models.DateTimeField()),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('consumed', 'Consumed'), ('wasted', 'Wasted')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'production batches',
                'ordering': ['produced_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='uniq_recipe_ingredient',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(help_text='Unit for this line (convertible to the target tracking unit)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryunit'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('manual_adjustment', 'Manual Adjustment'), ('order_deduction', 'Order Deduction'), ('order_reversal', 'Order Reversal'), ('production_consumption', 'Production Consumption'), ('wastage', 'Wastage'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('opening_stock', 'Opening Stock'), ('physical_count', 'Physical Count')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_items', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='unit',
            field=models.ForeignKey(help_text='Tracking unit for the prepared good (e.g. kg, portion)', on_delete=django.db.models.deletion.PROTECT, related_name='prepared_items', to='inventory.inventoryunit'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='prepared_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.prepareditem'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('ingredient__isnull', False)), fields=('recipe', 'ingredient'), name='uniq_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(condition=models.Q(('prepared_item__isnull', False)), fields=('recipe', 'prepared_item'), name='uniq_recipe_prepared_item'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('prepared_item__isnull', True)), models.Q(('ingredient__isnull', True), ('prepared_item__isnull', False)), _connector='OR'), name='recipe_line_single_target'),
        ),
        migrations.AddField(
            model_name='prepareditemcomponent',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_component_usages', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='prepareditemcomponent',
            name='prepared_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.prepareditem'),
        ),
        migrations.AddField(
            model_name='prepareditemcomponent',
            name='unit',
            field=models.ForeignKey(help_text='Unit for this line (convertible to ingredient.unit)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.inventoryunit'),
        ),
        migrations.AddField(
            model_name='preparedstocklevel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_stock_levels', to='core.location'),
        ),
        migrations.AddField(
            model_name='preparedstocklevel',
            name='prepared_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.prepareditem'),
        ),
        migrations.AddField(
            model_name='preparedstockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_movements', to='core.location'),
        ),
        migrations.AddField(
            model_name='preparedstockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preparedstockmovement',
            name='prepared_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.prepareditem'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='core.location'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='prepared_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_batches', to='inventory.prepareditem'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='produced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preparedstockmovement',
            name='production_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.productionbatch'),
        ),
        migrations.AddConstraint(
            model_name='prepareditem',
            constraint=models.UniqueConstraint(fields=('name', 'restaurant'), name='uniq_prepared_item_name_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='prepareditemcomponent',
            constraint=models.UniqueConstraint(fields=('prepared_item', 'ingredient'), name='uniq_prepared_component'),
        ),
        migrations.AddConstraint(
            model_name='prepareditemcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='prepared_component_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='preparedstocklevel',
            index=models.Index(fields=['location', 'quantity'], name='idx_prep_stock_loc_qty'),
        ),
        migrations.AddConstraint(
            model_name='preparedstocklevel',
            constraint=models.UniqueConstraint(fields=('prepared_item', 'location'), name='uniq_prepared_stocklevel'),
        ),
        migrations.AddConstraint(
            model_name='preparedstocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0'))), name='prepared_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['location', 'prepared_item', 'status'], name='idx_prodbatch_loc_item_status'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['expiry_at'], name='idx_prodbatch_expiry'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.UniqueConstraint(fields=('batch_number', 'location'), name='uniq_production_batch_number_location'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', Decimal('0'))), name='production_batch_remaining_non_negative'),
        ),
        migrations.AddIndex(
            model_name='preparedstockmovement',
            index=models.Index(fields=['location', 'prepared_item', 'created_at'], name='idx_prepmove_loc_item_date'),
        ),
        migrations.AddIndex(
            model_name='preparedstockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='idx_prepmove_reference'),
        ),
    ]
