# Generated by Django 6.0.6 on 2026-06-18 10:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffuser_location'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('calc_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='fixed', max_length=12)),
                ('service', models.CharField(choices=[('all', 'All'), ('delivery', 'Delivery'), ('dine_in', 'Dine-in'), ('takeaway', 'Takeaway')], default='delivery', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='menu/items/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ModerationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('VARIANT_PRICE', 'Variant Price'), ('CATALOGUE', 'Catalogue'), ('CATALOGUE_TAG', 'Catalogue Tag'), ('CATALOGUE_NAME', 'Catalogue Name'), ('CATALOGUE_DESC', 'Catalogue Description'), ('CATALOGUE_META', 'Catalogue Metadata'), ('MEDIA', 'Media')], max_length=20)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('meta_key', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('submitted_value', models.JSONField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('min_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['min_minutes'],
            },
        ),
        migrations.CreateModel(
            name='ServingInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('tag_type', models.CharField(choices=[('dietary', 'Dietary'), ('misc', 'Miscellaneous'), ('legal', 'Legally Sensitive'), ('info', 'Info'), ('gst', 'GST Classification'), ('cake_flavor', 'Cake Flavor'), ('cake_type', 'Cake Type')], default='misc', max_length=16)),
                ('selection', models.CharField(choices=[('single', 'Single-select'), ('multi', 'Multi-select')], default='multi', max_length=8)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tag_type', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('calc_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service', models.CharField(choices=[('all', 'All'), ('delivery', 'Delivery'), ('dine_in', 'Dine-in'), ('takeaway', 'Takeaway')], default='all', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'taxes',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('calc_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service', models.CharField(choices=[('all', 'All'), ('delivery', 'Delivery'), ('dine_in', 'Dine-in'), ('takeaway', 'Takeaway')], default='all', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TaxGroupTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='VariantCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='dietary_tags',
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='modifiergroup',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='price_delta',
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='max_select',
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='min_select',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='price_delta',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu/categories/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='box_columns',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='box_rows',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calorie_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbohydrate_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fat_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fiber_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='kind',
            field=models.CharField(choices=[('default', 'Default'), ('celebration-cake', 'Celebration Cake'), ('cake-message-on-the-cake', 'Message on the cake'), ('cake-message-on-bottom-of-cake', 'Message on bottom disc'), ('cake-message-on-chocolate-disc', 'Message on chocolate disc'), ('cake-birthday-candles', 'Birthday candles'), ('cake-birthday-knife', 'Cake knife'), ('cake-party-popper', 'Party popper'), ('box-fixed-piece', 'Box (fixed piece)')], default='default', max_length=40),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modifier',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='modifier',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modifier',
            name='kind',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('celebration-cake', 'Celebration Cake'), ('cake-message-on-the-cake', 'Message on the cake'), ('cake-message-on-bottom-of-cake', 'Message on bottom disc'), ('cake-message-on-chocolate-disc', 'Message on chocolate disc'), ('cake-birthday-candles', 'Birthday candles'), ('cake-birthday-knife', 'Cake knife'), ('cake-party-popper', 'Party popper'), ('box-fixed-piece', 'Box (fixed piece)')], max_length=40),
        ),
        migrations.AddField(
            model_name='modifier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='max_selection',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='min_selection',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='parent_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_groups', to='menu.modifier'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='variant',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variant',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='portion_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modifiergroup',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='menu.menuitem'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', False), ('parent_option__isnull', True)), models.Q(('menu_item__isnull', True), ('parent_option__isnull', False)), _connector='OR'), name='modifiergroup_single_parent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='items', to='menu.allergen'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meat_types',
            field=models.ManyToManyField(blank=True, related_name='items', to='menu.meattype'),
        ),
        migrations.AddField(
            model_name='menuitemmedia',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.menucategory'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menusubcategory'),
        ),
        migrations.AddField(
            model_name='moderationrecord',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_records', to='core.location'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='preparation_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.preparationtime'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.preparationtime'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['location', 'is_active'], name='menu_menuca_locatio_2937ff_idx'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='serving_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.servinginfo'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='menu.tag'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='menu_menuit_categor_ed897a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['kind'], name='menu_menuit_kind_4add0b_idx'),
        ),
        migrations.AddField(
            model_name='variant',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='menu.taxgroup'),
        ),
        migrations.AddField(
            model_name='taxgrouptax',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups_links', to='menu.tax'),
        ),
        migrations.AddField(
            model_name='taxgrouptax',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_taxes', to='menu.taxgroup'),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='tax_groups', through='menu.TaxGroupTax', to='menu.tax'),
        ),
        migrations.AddField(
            model_name='variant',
            name='portion_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.unit'),
        ),
        migrations.AddField(
            model_name='variantcharge',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_charges', to='menu.charge'),
        ),
        migrations.AddField(
            model_name='variantcharge',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='menu.variant'),
        ),
        migrations.DeleteModel(
            name='DietaryTag',
        ),
        migrations.AddConstraint(
            model_name='menusubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_subcategory_name'),
        ),
        migrations.AddIndex(
            model_name='moderationrecord',
            index=models.Index(fields=['location', 'status'], name='menu_modera_locatio_eb8e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationrecord',
            index=models.Index(fields=['entity_type', 'entity_id'], name='menu_modera_entity__7e77ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxgrouptax',
            constraint=models.UniqueConstraint(fields=('tax_group', 'tax'), name='uniq_taxgroup_tax'),
        ),
        migrations.AddConstraint(
            model_name='variantcharge',
            constraint=models.UniqueConstraint(fields=('variant', 'charge'), name='uniq_variant_charge'),
        ),
    ]
