# Generated by Django 6.0.6 on 2026-06-20 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_add_kitchen_menu_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='menu.taxgroup'),
        ),
        migrations.CreateModel(
            name='MenuListingVariantPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_prices', to='menu.menulisting')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_prices', to='menu.variant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('menu_listing', 'variant'), name='uniq_listing_variant_price')],
            },
        ),
    ]
