# Generated by Django 5.2.3 on 2026-06-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_variant_tax_group_menulistingvariantprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tracks_inventory',
            field=models.BooleanField(default=False, help_text='When True, stock availability is derived from linked recipes and ingredient stock levels at the item location.'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'tracks_inventory'], name='menu_menuit_categor_b71a04_idx'),
        ),
    ]
