# Generated by Django 6.0.6 on 2026-06-13 12:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('PULL', 'Pull'), ('PUSH', 'Push')], max_length=10)),
                ('sync_type', models.CharField(choices=[('QR_ORDER_PULL', 'QR Order Pull'), ('STATUS_UPDATE_PUSH', 'Status Update Push'), ('OFFLINE_ORDER_PUSH', 'Offline Order Push'), ('MENU_SYNC', 'Menu Sync')], max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=30)),
                ('payload_ref', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], max_length=15)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_holder', models.CharField(blank=True, max_length=64)),
                ('active_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.restaurant'),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_users', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=64)),
                ('node_label', models.CharField(blank=True, max_length=120)),
                ('station_codes', models.JSONField(default=list)),
                ('election_priority', models.IntegerField(default=10)),
                ('cluster_role', models.CharField(default='follower', max_length=20)),
                ('lan_host', models.CharField(blank=True, max_length=45)),
                ('lan_port', models.IntegerField(default=3001)),
                ('api_key_hash', models.CharField(max_length=128)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('promotion_pending', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('location', 'node_id'), name='uniq_location_node')],
            },
        ),
        migrations.CreateModel(
            name='NodeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=64)),
                ('config', models.JSONField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_configs', to='core.location')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('location', 'node_id'), name='uniq_node_config')],
            },
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('STATUS_CHANGED', 'Status Changed'), ('MENU_UPDATED', 'Menu Updated')], max_length=20)),
                ('order_ref', models.UUIDField(db_index=True, null=True)),
                ('payload', models.JSONField()),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('acked_by_node', models.CharField(blank=True, max_length=64)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='core.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'acked_at', 'sequence'], name='core_syncou_locatio_f19223_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'sequence'), name='uniq_outbox_location_seq')],
            },
        ),
    ]
