# Generated by Django 6.0.6 on 2026-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_printroute_drop_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('waiter', 'Waiter'), ('kiosk', 'Kiosk')], default='staff', max_length=20),
        ),
    ]
