# Generated by Django 6.0.6 on 2026-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_staffuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnode',
            name='cluster_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
