# Generated by Django 5.2.3 on 2026-06-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_locationnode_cluster_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='core.location'),
        ),
    ]
