# Generated by Django 6.0.6 on 2026-06-18 12:12

import secrets

from django.db import migrations, models


def seed_signing_secrets(apps, schema_editor):
    Restaurant = apps.get_model('core', 'Restaurant')
    for r in Restaurant.objects.filter(jwt_signing_secret=''):
        r.jwt_signing_secret = secrets.token_hex(32)
        r.save(update_fields=['jwt_signing_secret'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='jwt_signing_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(seed_signing_secrets, migrations.RunPython.noop),
    ]
